---
apiVersion: xl-release/v1
kind: Templates
spec:
- directory: Compuware Webinar Nov 12th
  children:
  - template: Compuware - REST
    phases:
    - phase: QA
      tasks:
      - name: Deployments
        type: xlrelease.ParallelGroup
        tasks:
        - name: Deploy onto websphere
          type: xldeploy.Deploy
          deploymentPackage: PetClinic-wlp/1.0
          deploymentEnvironment: WLP - defaultServer
        - name: ISPW
          type: xlrelease.ParallelGroup
          tasks:
          - name: Get release info
            type: ispwServices.GetReleaseInformation
            srid: ispw
            relId: ${ISPW_RELEASE_ID}
          - name: Create a new release
            type: ispwServices.CreateRelease
            srid: ispw
            application: ${ISPW_APPLICATION}
            stream: ${ISPW_STREAM}
            description: ${ISPW_RELEASE_DESCRIPTION}
            relId: ${ISPW_RELEASE_ID}
          - name: Validate ISPW release components
            type: xlrelease.Task
          - name: Get deployment wait task id
            type: xlr.GetTaskId
            taskTitle: Placeholder for finishing deployment
            variableMapping:
              pythonScript.taskId: ${ISPW_QA_DEPL_TASK_ID}
          - name: Run deployment
            type: ispwServices.Deploy
            srid: ispw
            runtimeConfiguration: CWCC
            callbackTaskId: ${ISPW_QA_DEPL_TASK_ID}
            callbackUrl: http://dtw-xebialabs.nasa.cpwr.corp:5516
            callbackUsername: admin
            level: ${ISPW_LEVEL}
          - name: Placeholder for finishing deployment
            type: xlrelease.Task
            owner: admin
          links:
          - name: Applications\/Folder49fcc9cbb62a41d089a40d03924ec038\/Release06090ab3e11d46bb93da78f4e442b271\/Phase2033345\/Task6872401\/Task2331482\/Link3327597
            type: xlrelease.Link
            source: Get deployment wait task id
            target: Placeholder for finishing deployment
          - name: Applications\/Folder49fcc9cbb62a41d089a40d03924ec038\/Release06090ab3e11d46bb93da78f4e442b271\/Phase2033345\/Task6872401\/Task2331482\/Link6008439
            type: xlrelease.Link
            source: Get release info
            target: Create a new release
          - name: Applications\/Folder49fcc9cbb62a41d089a40d03924ec038\/Release06090ab3e11d46bb93da78f4e442b271\/Phase2033345\/Task6872401\/Task2331482\/Link1531888
            type: xlrelease.Link
            source: Create a new release
            target: Validate ISPW release components
          - name: Applications\/Folder49fcc9cbb62a41d089a40d03924ec038\/Release06090ab3e11d46bb93da78f4e442b271\/Phase2033345\/Task6872401\/Task2331482\/Link2764447
            type: xlrelease.Link
            source: Validate ISPW release components
            target: Run deployment
      - name: end2end_test
        client: Compuware Topaz
        type: topaz.runtest
        project: C:\Users\wlee\CWXTCOB_TTT
        testsuite: CWXTCOB_Scenario.testscenario
        jcl: Runner.jcl
        variableMapping:
          pythonScript.sysExitCode: ${system-exit-code}
      color: '#68b749'
    - phase: Pre prod
      tasks:
      - name: Deployments
        type: xlrelease.ParallelGroup
        tasks:
        - name: Deploy onto websphere
          type: xldeploy.Deploy
          deploymentPackage: PetClinic-wlp/1.0
          deploymentEnvironment: WLP - defaultServer
        - name: ISPW
          type: xlrelease.ParallelGroup
          tasks:
          - name: Validate ISPW release components
            type: xlrelease.Task
          - name: Get preprod promote wait task id
            type: xlr.GetTaskId
            taskTitle: preprod promote wait task id
            variableMapping:
              pythonScript.taskId: ${ISPW_PREPROD_PROMOTE_TASK_ID}
          - name: Get preprod deploy wait task id
            type: xlr.GetTaskId
            taskTitle: preprod deploy wait task id
            variableMapping:
              pythonScript.taskId: ${ISPW_PREPROD_DEPL_TASK_ID}
          - name: Promote
            type: ispwServices.Promote
            srid: ispw
            runtimeConfiguration: CWCC
            callbackTaskId: ${ISPW_PREPROD_PROMOTE_TASK_ID}
            callbackUrl: http://dtw-xebialabs.nasa.cpwr.corp:5516
            callbackUsername: admin
            callbackPassword: !value xlrelease_password
            level: ${ISPW_LEVEL}
          - name: Run deployment
            type: ispwServices.Deploy
            srid: ispw
            callbackUrl: http://dtw-xebialabs.nasa.cpwr.corp:5516
            callbackUsername: admin
            callbackPassword: !value xlrelease_password
            level: ${ISPW_LEVEL_STG}
          - name: preprod promote wait task id
            type: xlrelease.Task
            owner: admin
          - name: preprod deploy wait task id
            type: xlrelease.Task
            owner: admin
          links:
          - name: Applications\/Folder49fcc9cbb62a41d089a40d03924ec038\/Release06090ab3e11d46bb93da78f4e442b271\/Phase799217\/Task6872401\/Task4010347\/Link4372122
            type: xlrelease.Link
            source: Get preprod deploy wait task id
            target: preprod deploy wait task id
          - name: Applications\/Folder49fcc9cbb62a41d089a40d03924ec038\/Release06090ab3e11d46bb93da78f4e442b271\/Phase799217\/Task6872401\/Task4010347\/Link1368733
            type: xlrelease.Link
            source: Get preprod promote wait task id
            target: preprod promote wait task id
          - name: Applications\/Folder49fcc9cbb62a41d089a40d03924ec038\/Release06090ab3e11d46bb93da78f4e442b271\/Phase799217\/Task6872401\/Task4010347\/Link6279116
            type: xlrelease.Link
            source: Promote
            target: Run deployment
          - name: Applications\/Folder49fcc9cbb62a41d089a40d03924ec038\/Release06090ab3e11d46bb93da78f4e442b271\/Phase799217\/Task6872401\/Task4010347\/Link4877082
            type: xlrelease.Link
            source: Validate ISPW release components
            target: Promote
      - name: Approve pre prod
        type: xlrelease.GateTask
        conditions:
        - name: Testing done?
          type: xlrelease.GateCondition
      color: '#009CDB'
    - phase: Prod
      tasks:
      - name: Deployments
        type: xlrelease.ParallelGroup
        tasks:
        - name: Deploy onto websphere
          type: xldeploy.Deploy
          deploymentPackage: PetClinic-wlp/1.0
          deploymentEnvironment: WLP - defaultServer
        - name: ISPW
          type: xlrelease.ParallelGroup
          tasks:
          - name: Validate ISPW release components
            type: xlrelease.Task
          - name: Get prod promote wait task id
            type: xlr.GetTaskId
            taskTitle: prod promote wait task id
            variableMapping:
              pythonScript.taskId: ${ISPW_PROD_PROMOTE_TASK_ID}
          - name: Get prod deploy wait task id
            type: xlr.GetTaskId
            taskTitle: prod deploy wait task id
            variableMapping:
              pythonScript.taskId: ${ISPW_PROD_DEPL_TASK_ID}
          - name: Promote
            type: ispwServices.Promote
            srid: ispw
            runtimeConfiguration: CWCC
            callbackTaskId: ${ISPW_PROD_PROMOTE_TASK_ID}
            callbackUrl: http://dtw-xebialabs.nasa.cpwr.corp:5516
            callbackUsername: admin
            relId: XEBIAP3
            level: ${ISPW_LEVEL_STG}
          - name: Run deployment
            type: ispwServices.Deploy
            srid: ispw
            runtimeConfiguration: CWCC
            callbackTaskId: ${ISPW_PROD_DEPL_TASK_ID}
            callbackUrl: http://dtw-xebialabs.nasa.cpwr.corp:5516
            callbackUsername: admin
            level: ${ISPW_LEVEL_STG}
          - name: prod promote wait task id
            type: xlrelease.Task
            owner: admin
          - name: prod deploy wait task id
            type: xlrelease.Task
            owner: admin
          links:
          - name: Applications\/Folder49fcc9cbb62a41d089a40d03924ec038\/Release06090ab3e11d46bb93da78f4e442b271\/Phase6280420\/Task6872401\/Task1845049\/Link4877082
            type: xlrelease.Link
            source: Validate ISPW release components
            target: Promote
          - name: Applications\/Folder49fcc9cbb62a41d089a40d03924ec038\/Release06090ab3e11d46bb93da78f4e442b271\/Phase6280420\/Task6872401\/Task1845049\/Link6279116
            type: xlrelease.Link
            source: Promote
            target: Run deployment
          - name: Applications\/Folder49fcc9cbb62a41d089a40d03924ec038\/Release06090ab3e11d46bb93da78f4e442b271\/Phase6280420\/Task6872401\/Task1845049\/Link1368733
            type: xlrelease.Link
            source: Get prod promote wait task id
            target: prod promote wait task id
          - name: Applications\/Folder49fcc9cbb62a41d089a40d03924ec038\/Release06090ab3e11d46bb93da78f4e442b271\/Phase6280420\/Task6872401\/Task1845049\/Link4372122
            type: xlrelease.Link
            source: Get prod deploy wait task id
            target: prod deploy wait task id
      - name: Get Set information
        type: ispwServices.GetSetInformation
        srid: ispw
        setId: S000004743
      color: '#663366'
    variables:
    - type: xlrelease.StringVariable
      key: ISPW_RELEASE_ID
      label: ISPW Release id
    - type: xlrelease.StringVariable
      key: ISPW_RELEASE_DESCRIPTION
      label: ISPW Release description
    - type: xlrelease.StringVariable
      key: ISPW_APPLICATION
      label: ISPW Application
      value: peka
    - type: xlrelease.StringVariable
      key: ISPW_LEVEL
      label: ISPW Level Dev
      value: qa1
    - type: xlrelease.StringVariable
      key: ISPW_USER
      label: ISPW User
      value: icapss0
    - type: xlrelease.StringVariable
      key: ISPW_LEVEL_STG
      label: ISPW Level QA
      value: stg
    - type: xlrelease.StringVariable
      key: ISPW_LEVEL_PRD
      label: ISPW Level Production
      value: prd
    - type: xlrelease.StringVariable
      key: ISPW_STREAM
      label: ISPW Stream
      value: SNOW
    - type: xlrelease.StringVariable
      key: ISPW_QA_DEPL_TASK_ID
      requiresValue: false
      showOnReleaseStart: false
    - type: xlrelease.StringVariable
      key: ISPW_PREPROD_PROMOTE_TASK_ID
      requiresValue: false
      showOnReleaseStart: false
    - type: xlrelease.StringVariable
      key: ISPW_PREPROD_DEPL_TASK_ID
      requiresValue: false
      showOnReleaseStart: false
    - type: xlrelease.StringVariable
      key: ISPW_PROD_PROMOTE_TASK_ID
      requiresValue: false
      showOnReleaseStart: false
    - type: xlrelease.StringVariable
      key: ISPW_PROD_DEPL_TASK_ID
      requiresValue: false
      showOnReleaseStart: false
    - type: xlrelease.StringVariable
      key: system-exit-code
      requiresValue: false
      value: -1
    scriptUsername: admin
    scriptUserPassword: !value xlrelease_password
    riskProfile: Default risk profile
  - type: xlrelease.Dashboard
    tiles:
    - name: Release progress
      type: xlrelease.ReleaseProgressTile
    - name: Release timeline
      type: xlrelease.TimelineTile
      row: 2
    - name: Release health
      type: xlrelease.ReleaseHealthTile
    - name: Release summary
      type: xlrelease.ReleaseSummaryTile
      row: 3
    - name: XL Deploy deployments
      type: xlrelease.XLDeployTile
      row: 0
      col: 0
    - name: ISPW Deployments
      type: ispwServices.ISPWTile
      row: 1
      col: 0
      action: Deploy
    - name: ISPW Promotions
      type: ispwServices.ISPWTile
      row: 1
      col: 1
      action: Promote
    - name: ISPW Create Release
      type: ispwServices.ISPWTile
      row: 1
      col: 2
      action: CreateRelease
    parentTemplate: Compuware - REST
