---
apiVersion: xl-release/v1
kind: Templates
spec:
- directory: Compuware Webinar Nov 12th
  - template: topaz total test
    scheduledStartDate: 2019-10-22T13:00:00Z
    phases:
    - phase: New Phase
      tasks:
      - name: end2end_test
        type: topaz.runtest
        project: C:\Users\wlee\CWXTCOB_TTT
        testsuite: CWXTCOB_Scenario.testscenario
        jcl: Runner.jcl
        variableMapping:
          pythonScript.sysExitCode: ${system-exit-code}
    variables:
    - type: xlrelease.StringVariable
      key: system-exit-code
      requiresValue: false
      value: -1