---
apiVersion: xl-release/v1
kind: Templates
spec:
- directory: Compuware Webinar Nov 12th
  children:
  - name: Xebialabs JIRA
    type: jira.Server
    url: !value jira_url
    username: !value jira_username
    password: !value jira_password
  - name: Compuware ISPW
    type: ispwServices.Server
    url: http://ispw:8080/
    authenticationMethod: Basic
    cesToken: !value ispw_password
    enableSslVerification: false
  - name: Topaz Box
    type: host.Unix
    address: topaz-box
    title: Topaz Box
    username: topaztest
    password: !value xlrelease_password
    connectionType: SCP
    port: 22
  - name: Compuware Topaz
    type: topaz.client
    unixClientHost: Topaz Box
    serverUrl: 192.168.1.1
    serverPort: 1982
    username: henkie
    password: "********"
    clientHost: Unix